///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_git_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a6f658c8-cb85-4a1f-810d-a881c2ec95b7")]
    public partial class rx_git_projRepository : RepoGenBaseFolder
    {
        static rx_git_projRepository instance = new rx_git_projRepository();

        /// <summary>
        /// Gets the singleton class instance representing the rx_git_projRepository element repository.
        /// </summary>
        [RepositoryFolder("a6f658c8-cb85-4a1f-810d-a881c2ec95b7")]
        public static rx_git_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_git_projRepository() 
            : base("rx_git_projRepository", "/", null, 0, false, "a6f658c8-cb85-4a1f-810d-a881c2ec95b7", ".\\RepositoryImages\\rx_git_projRepositorya6f658c8.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a6f658c8-cb85-4a1f-810d-a881c2ec95b7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class rx_git_projRepositoryFolders
    {
    }
#pragma warning restore 0436
}
